### ISSUE TITLE
[DOCUMENTATION] Complete the example for sending relays

### ISSUE THREAD

**Issue by adshmh** [pokt-network/shannon-sdk#16]
## Objective

Following the refactoring of the SDK, most recently in PR #15, it seems very helpful to have a complete example to guide the users in using the SDK for sending relays.

## Origin Document

Here is a snapshot of a code snippet from `relay_test.go` which shows a generally correct, but incomplete example of how to send a relay request using the SDK:

![image](https://github.com/pokt-network/shannon-sdk/assets/23505281/8e287af0-2639-4e62-bc03-f1dce3bd4fdc)

## Goals

- Complete the above example
- Update any comments as needed, more specifically target the godoc generated document.

## Deliverables

- [ ] Updated example for sending a relay (in `relay_test.go`)
- [ ] Updated comments on functions/components involved in the above example.
- ...

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

**Creator**: [adshmh]

**Comment by red-0ne** [comment]
Closed as per #15 and #19
